from sqlalchemy.orm import Session

from src.models.exercise import Exercise as ExerciseModel
from src.services.database import Base, engine
from src.services.exercise_db import add_exercise


def seed_exercises(db: Session):
    # Clear existing data
    db.query(ExerciseModel).delete()
    db.commit()

    exercises = [
        ExerciseModel(
            id=1,
            name="Calf Raise",
            description="A lower body exercise.",
            instructions="Stand with your torso upright, your feet hip-width apart, and your toes pointing forward. Raise your heels off the floor and squeeze your calves. Return to the starting position, by slowly lowering your heels, and repeat.",
            target_muscles=["calves"],
            difficulty="Easy",
            category="Strength",
        ),
        ExerciseModel(
            id=2,
            name="Rowing",
            description="A back exercise.",
            instructions="Use a rowing machine or barbell and begin by pushing with your legs, while still bracing and contracting your core. When your legs are straight, hinge at the hips and lean back to about 45 degrees. The last movement is from your arms as you pull the handle towards your torso, a few inches above your belly button. Note the order of body movements: legs, core, hips and shoulders, arms.",
            target_muscles=["back", "biceps"],
            difficulty="Medium",
            category="Strength",
        ),
        ExerciseModel(
            id=3,
            name="Lat Pulldown",
            description="A back exercise.",
            instructions="Step Place your knees under the provided pads. Position the pads so that your thighs are not able to raise up off the bench. Grasp the lat bar with a little wider than shoulder-width grip. This is the starting position. Begin exercise by pulling the bar down to your upper chest. Focus on using your lats to pull the bar down and not your arms. Slowly reverse movement back to starting position. This completes one rep.",
            target_muscles=["back", "biceps"],
            difficulty="Medium",
            category="Strength",
        ),
        ExerciseModel(
            id=4,
            name="Chest Fly",
            description="A chest exercise.",
            instructions="Hold 1 dumbbell in each hand. Start with your arms at chest level at your sides, elbows bent and pointing out. Slowly exhale and lift your arms above your chest. Inhale and slowly lower your arms to your sides to the starting position.",
            target_muscles=["chest"],
            difficulty="Medium",
            category="Strength",
        ),
        ExerciseModel(
            id=5,
            name="Leg Curl",
            description="A lower body exercise.",
            instructions="Stand with feet hip-width apart. Shift your weight onto one leg and bend the other at the knee, bringing that foot closer to the butt. Lower the foot and repeat on the other side. Do up to 10 reps, at least three times a week, initially.",
            target_muscles=["hamstrings"],
            difficulty="Medium",
            category="Strength",
        ),
        ExerciseModel(
            id=6,
            name="Leg Extension",
            description="A lower body exercise.",
            instructions="The leg pad should in front of the top of your ankles, feet facing forward. Grip the bars on either side of the seat. Use your quads to extend your legs up until they are fully straight. Hold this position for a second and squeeze your quads before slowly lowering your legs back to the starting position.",
            target_muscles=["quadriceps"],
            difficulty="Medium",
            category="Strength",
        ),
        ExerciseModel(
            id=7,
            name="Hip Thrust",
            description="A lower body exercise.",
            instructions="Drive your hips up towards the ceiling until your body forms a straight line from your knees to your shoulders.",
            target_muscles=["glutes"],
            difficulty="Medium",
            category="Strength",
        ),
        ExerciseModel(
            id=8,
            name="Side Lunge",
            description="A lower body exercise.",
            instructions="Bend your left knee as you step outward and keep your hips back. Release the position by pushing off your left foot to return to the starting position. Perform one set of side lunges on your left leg, then switch to your right leg.",
            target_muscles=["quadriceps", "glutes"],
            difficulty="Medium",
            category="Strength",
        ),
        ExerciseModel(
            id=9,
            name="Front Raise",
            description="A shoulder exercise.",
            instructions="Perform front raises by standing and using an overhand grip to lift a pair of dumbbells from the front of your thighs to shoulder level in front of your body.",
            target_muscles=["shoulders"],
            difficulty="Medium",
            category="Strength",
        ),
        ExerciseModel(
            id=10,
            name="Rear Delt Fly",
            description="A shoulder exercise.",
            instructions="Holding a dumbbell in each hand, take a seat on a bench and lean forwards at the hips so that your torso is at a 30–45-degree angle. Keep your shoulders pinned back and your chin tucked to ensure a neutral spine and allow your arms to extend in front of you. To commence the reps, maintain a soft bend in the elbows as you sweep the dumbbells outwards to the sides until they are in line with your torso. Slowly reverse the movement to return the dumbbells to the starting position.",
            target_muscles=["rear deltoids"],
            difficulty="Medium",
            category="Strength",
        ),
        ExerciseModel(
            id=11,
            name="Push-up",
            description="A basic push-up exercise.",
            instructions="With your legs extended back, place the hands below the shoulders, slightly wider than shoulder-width apart.",
            target_muscles=["chest", "triceps"],
            difficulty="Easy",
            category="Strength",
        ),
        ExerciseModel(
            id=12,
            name="Squat",
            description="A basic squat exercise.",
            instructions="Stand with your feet slightly greater than shoulder-width apart and your toes pointing ahead. Slowly descend, bending through the hips, knees and ankles. Stop when your knees reach a 90-degree angle. Then return to the starting position.",
            target_muscles=["quadriceps", "glutes"],
            difficulty="Easy",
            category="Strength",
        ),
        ExerciseModel(
            id=13,
            name="Plank",
            description="A core strengthening exercise.",
            instructions="Lie on the stomach with the feet together and the forearms on the ground with elbows under the shoulders. Draw in the belly button, brace, and squeeze the glute muscles. Lift the body off of the floor and form a straight line from head to heel. Return to the starting position.",
            target_muscles=["core"],
            difficulty="Medium",
            category="Core",
        ),
        ExerciseModel(
            id=14,
            name="Lunge",
            description="A lower body exercise.",
            instructions="Start by standing up comfortably. Step ahead with one foot and lean forward until your knee reaches a 90-degree angle and your rear knee is parallel to the ground. Then return to the starting position.",
            target_muscles=["quadriceps", "glutes"],
            difficulty="Medium",
            category="Strength",
        ),
        ExerciseModel(
            id=15,
            name="Bicep Curl",
            description="An arm exercise.",
            instructions="Hold a dumbbell with your palm facing upward. Slowly curl the weight up by bending your elbow, keeping your elbow close to your body. Then slowly lower the weight to the starting position.",
            target_muscles=["biceps"],
            difficulty="Easy",
            category="Strength",
        ),
        ExerciseModel(
            id=16,
            name="Tricep Dip",
            description="An arm exercise.",
            instructions="Grab your bars with your palms facing inward and your arms straight. Slowly lower until your elbows are at right angles, ensuring they stay tucked against your body and don't flare out. Drive yourself back up to the top and repeat.",
            target_muscles=["triceps"],
            difficulty="Medium",
            category="Strength",
        ),
        ExerciseModel(
            id=17,
            name="Deadlift",
            description="A full-body exercise.",
            instructions="bend down, grab an object on the floor, and lift it off the floor.",
            target_muscles=["hamstrings", "glutes", "back"],
            difficulty="Hard",
            category="Strength",
        ),
        ExerciseModel(
            id=18,
            name="Bench Press",
            description="A chest exercise.",
            instructions="Hold the weight directly over the shoulders, arms slightly wider than shoulder height. Push the weight up until your arms are angled at 45 degrees at the top. Slowly lower the weight back down to chest height, elbows out to the sides. Repeat the press and perform around 5 reps or more.",
            target_muscles=["chest", "triceps"],
            difficulty="Hard",
            category="Strength",
        ),
        ExerciseModel(
            id=19,
            name="Pull-up",
            description="An upper body exercise.",
            instructions="Step 1: Grab the pull-up bar with a 1-1.5x shoulder width grip, palms facing away from you. Pull the body upward driving the chest toward the bar/handles until the arms/elbows are packed into the side of the body. Reverse the pattern and return to starting position.",
            target_muscles=["back", "biceps"],
            difficulty="Hard",
            category="Strength",
        ),
        ExerciseModel(
            id=20,
            name="Leg Press",
            description="A lower body exercise.",
            instructions="Grab onto the handles near your hips and get ready to press! Take a deep breath, then brace your core like you're doing a crunch. To complete the movement, engage your legs, pushing the weight away from your body until your knees are extended, and exhale while you push.",
            target_muscles=["quadriceps", "glutes"],
            difficulty="Medium",
            category="Strength",
        ),
        ExerciseModel(
            id=21,
            name="Shoulder Press",
            description="A shoulder exercise.",
            instructions="Stand with your feet shoulder-width apart and hold a dumbbell in each hand. With your palms facing forward and your elbows under your wrists, position the dumbbells at your shoulders. Push the dumbbells up and fully extend your arms. Lower the dumbbells back down to your shoulders and repeat the movement until the set is complete.",
            target_muscles=["shoulders"],
            difficulty="Medium",
            category="Strength",
        ),
        ExerciseModel(
            id=22,
            name="Crunch",
            description="An abdominal exercise.",
            instructions="Lie on your back with the arms extended above your head, clasp your hands and raise the legs toward the ceiling. Lift your shoulders, open the legs and chop your hands through your legs. Return to the starting position and repeat until the set is complete.",
            target_muscles=["abs"],
            difficulty="Easy",
            category="Core",
        ),
        ExerciseModel(
            id=23,
            name="English Twist",
            description="An abdominal exercise.",
            instructions="Lie down with your legs bent at the knees. Elevate your upper body so that it creates a V shape with your thighs. Twist your torso to the right, and then reverse the motion, twisting it to the left. Repeat this movement until the set is complete.",
            target_muscles=["obliques"],
            difficulty="Medium",
            category="Core",
        ),
        ExerciseModel(
            id=24,
            name="Mountain Climber",
            description="A full-body exercise.",
            instructions="Start on your hands and toes. Bending at the knee, bring your left knee forward directly under your chest while keeping your right leg straight. Quickly alternate legs while keeping your core muscles tight. Try to keep your body in a straight line without dipping in the low back.",
            target_muscles=["core", "legs"],
            difficulty="Medium",
            category="Cardio",
        ),
        ExerciseModel(
            id=25,
            name="Burpee",
            description="A full-body exercise.",
            instructions="getting onto the floor in a plank position, kicking your legs behind you, performing a partial press up, jumping your legs back in, and standing up with a jump.",
            target_muscles=["full body"],
            difficulty="Hard",
            category="Cardio",
        ),
        ExerciseModel(
            id=26,
            name="Jumping Jack",
            description="A cardio exercise.",
            instructions="Stand with your feet together, knees slightly bent, and arms at your sides. Jump your legs apart while raising your arms overhead. Jump your legs back together, returning to your starting position.",
            target_muscles=["full body"],
            difficulty="Easy",
            category="Cardio",
        ),
        ExerciseModel(
            id=27,
            name="High Knees",
            description="A cardio exercise.",
            instructions="Stand straight with your feet shoulder-width apart. Face forward and open your chest. Bring your knees up to waist level and then slowly land on the balls of your feet. Repeat until the set is complete.",
            target_muscles=["legs", "core"],
            difficulty="Medium",
            category="Cardio",
        ),
        ExerciseModel(
            id=28,
            name="Bicycle Crunch",
            description="An abdominal exercise.",
            instructions="Lie on your back, lift your shoulders off the mat and raise both legs. Bring one knee and the opposing elbow close to each other by crunching to one side, and fully extend the other leg. Return to the starting position and then crunch to the opposite side. Repeat until the set is complete.",
            target_muscles=["abs", "obliques"],
            difficulty="Medium",
            category="Core",
        ),
        ExerciseModel(
            id=29,
            name="Leg Raise",
            description="An abdominal exercise.",
            instructions="Lie on your back with one leg resting straight on the floor and the other bent at the knee (with your foot flat on the ground). Raise your straight leg toward the ceiling, focusing on keeping your leg straight as you do so. Hold for a few seconds and relax your leg back to the floor.",
            target_muscles=["abs"],
            difficulty="Medium",
            category="Core",
        ),
        ExerciseModel(
            id=30,
            name="Side Plank",
            description="A core exercise.",
            instructions="Lie on your side with your knees bent. Prop your upper body up on your elbow, with your elbow under your shoulder. Raise your hips off the floor. Keep your body straight by tightening your belly and buttocks muscles. Hold for about 6 seconds. Repeat 3 to 5 times on each side.",
            target_muscles=["obliques"],
            difficulty="Medium",
            category="Core",
        ),
    ]
    for exercise in exercises:
        add_exercise(db, exercise)


def main():
    Base.metadata.create_all(bind=engine)
    db = Session(bind=engine)
    seed_exercises(db)


if __name__ == "__main__":
    main()
